[project]
name = "dungeoncrawler"
version = "0.9.0b1"
description = "Dungeon Crawler game"
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "Dungeon Crawler Team"}]
dependencies = []

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["dungeoncrawler"]
include-package-data = true
