name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'coverage.svg'
      - '.github/workflows/pages.yml'
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'coverage.svg'
      - '.github/workflows/pages.yml'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
      - run: python -m pip install --upgrade pip
      - run: pip install black isort flake8
      - name: Run linters
        run: |
          isort --profile black --check-only .
          black --check .
          flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt pytest coverage coverage-badge
      - name: Run tests
        run: |
          coverage run -m pytest -q
          coverage report
      - name: Generate coverage badge (no commit)
        run: coverage-badge -f -o coverage.svg
