name: Auto-format (Black + isort)

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, reopened, synchronize]
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "requirements-dev.txt"
      - ".isort.cfg"
      - "setup.cfg"
      - ".flake8"
      - ".editorconfig"
  push:
    branches: ["**"]
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "requirements-dev.txt"
      - ".isort.cfg"
      - "setup.cfg"
      - ".flake8"
      - ".editorconfig"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-format-${{ github.event_name }}-${{ github.ref || github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      # Checkout the *right* branch
      - name: Checkout for PR (same repo)
        if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Checkout for PR (fork)
        if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name != github.repository }}
        uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          persist-credentials: false

      - name: Checkout for push
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install formatters (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      # Rebase so our formatting commit sits on the latest remote tip
      - name: Rebase onto remote tip
        shell: bash
        run: |
          BRANCH="${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.ref || github.ref_name }}"
          git fetch origin "${BRANCH}" --depth=1 || true
          git pull --rebase origin "${BRANCH}" || true

      - name: Run formatters (isort then Black)
        run: |
          isort --profile black .
          black .

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push
        if: steps.changes.outputs.changed == 'true'
        shell: bash
        run: |
          BRANCH="${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.ref || github.ref_name }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Apply Black and isort formatting"
          # Try normal push; if remote moved again, rebase and push
          git push origin HEAD:"${BRANCH}" || (git pull --rebase origin "${BRANCH}" && git push origin HEAD:"${BRANCH}")
