name: Auto-format via PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1-5'  # weekdays 08:00 UTC
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: format-pr
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
      - run: python -m pip install --upgrade pip
      - run: pip install ".[dev]"
      - name: Run formatters
        run: |
          black .
          isort --profile black .
      - name: Create or update PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/formatting
          title: "Apply Black and isort formatting"
          commit-message: "Apply Black and isort formatting"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          body: "Automated formatting (Black + isort)."
          delete-branch: true
