name: Auto-format (Black + isort)

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "requirements*.txt"
      - ".isort.cfg"
      - "setup.cfg"
      - ".flake8"
      - ".editorconfig"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-format-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install formatters (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install isort==6.0.1 black==25.1.0

      - name: Run formatters (isort then Black)
        run: |
          isort --profile black .
          black .

      - name: Detect changes
        id: diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit formatting (same-repo PRs)
        if: ${{ steps.diff.outputs.changed == 'true' && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Apply Black + isort formatting"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Create patch for forks
        if: ${{ steps.diff.outputs.changed == 'true' && github.event.pull_request.head.repo.full_name != github.repository }}
        run: git diff > formatting.patch

      - name: Upload patch artifact (fork PRs)
        if: ${{ steps.diff.outputs.changed == 'true' && github.event.pull_request.head.repo.full_name != github.repository }}
        uses: actions/upload-artifact@v4
        with:
          name: formatting.patch
          path: formatting.patch
