name: Auto-format via PR

on:
  workflow_dispatch:      # manual "Run workflow" button
  schedule:
    - cron: '0 8 * * *'   # optional: daily at 08:00 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: format-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install formatters
        run: |
          pip install --upgrade pip
          pip install black isort

      - name: Run formatters
        run: |
          black .
          isort .

      - name: Create or update PR with changes
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ci/formatting
          title: "Apply Black and isort formatting"
          commit-message: "Apply Black and isort formatting"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          body: |
            This PR applies automated formatting (Black + isort).
          delete-branch: true
