name: Auto-format via PR

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: format-pr
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            pyproject.toml
      - run: python -m pip install --upgrade pip
      - run: pip install ".[dev]"
      - name: Run formatters
        run: |
          black .
          isort --profile black .
      - name: Create or update PR with changes (fork)
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Apply Black and isort formatting"
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
          push-to-fork: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Create or update PR with changes (same repo)
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Apply Black and isort formatting"
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: ${{ github.head_ref }}
